# Generated by Django 4.2.3 on 2023-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Название")),
                ("video_file", models.FileField(upload_to="videos/")),
                ("date", models.DateField(verbose_name="Дата")),
            ],
        ),
    ]
