# Generated by Django 4.2.3 on 2023-09-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Название")),
                (
                    "video_file",
                    models.FileField(upload_to="media/videos", verbose_name="Файл"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("user", models.CharField(max_length=30, verbose_name="Пользователь")),
            ],
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео",},
        ),
    ]
